Repository TopleProject/mamully, pull requests merged in 2024-09, with the labels that each got.

#10 refactor docker-compose 파일 수정
  docker-compose.yml
Labels: refactor

#12 feat Swagger 연동 완료
  toyProject/build.gradle
  toyProject/src/main/java/com/mamully/toyProject/ToyProjectApplication.java
  toyProject/src/main/java/com/mamully/toyProject/config/SwaggerConfig.java
  toyProject/src/main/resources/application.properties
  toyProject/src/main/resources/application.yml
Labels: feat

#14 feat JPA 테스트 완료 및 config 파일 추가
  docker-compose.yml
  toyProject/DockerFile
  toyProject/build.gradle
  toyProject/src/main/java/com/mamully/toyProject/config/Webconfig.java
  toyProject/src/main/java/com/mamully/toyProject/test/controllers/TestController.java
  toyProject/src/main/java/com/mamully/toyProject/test/entities/Test.java
  toyProject/src/main/java/com/mamully/toyProject/test/repositories/TestRepository.java
  toyProject/src/main/java/com/mamully/toyProject/test/services/TestDTO.java
  toyProject/src/main/java/com/mamully/toyProject/test/services/TestService.java
  toyProject/src/main/resources/application.yml
Labels: feat, refactor, chore

#16 feat Mybatis 연동 및 조회 테스트 완료
  toyProject/build.gradle
  toyProject/src/main/java/com/mamully/toyProject/config/MybatisConfig.java
  toyProject/src/main/java/com/mamully/toyProject/test/controllers/TestController.java
  toyProject/src/main/java/com/mamully/toyProject/test/entities/Test.java
  toyProject/src/main/java/com/mamully/toyProject/test/mappers/TestMapper.java
  toyProject/src/main/java/com/mamully/toyProject/test/services/TestService.java
  toyProject/src/main/resources/application.yml
  toyProject/src/main/resources/com/mamully/toyProject/test/mappers/TestMapper.xml
  toyProject/src/test/java/com/mamully/toyProject/test/service/TestServiceTest.java
Labels: feat, refactor, test

#18 refactor CQRS 패턴 디렉토리 수정 및 추가 완료
  toyProject/src/main/java/com/mamully/toyProject/config/MybatisConfig.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/controllers/TestController.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/entities/Test.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/repositories/TestRepository.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/services/TestDTO.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/services/TestService.java
  toyProject/src/main/java/com/mamully/toyProject/test/query/controllers/TestQueryController.java
  toyProject/src/main/java/com/mamully/toyProject/test/query/mappers/TestMapper.java
  toyProject/src/main/java/com/mamully/toyProject/test/query/services/TestQueryDTO.java
  toyProject/src/main/java/com/mamully/toyProject/test/query/services/TestQueryService.java
  toyProject/src/main/resources/com/mamully/toyProject/test/query/mappers/TestMapper.xml
  toyProject/src/test/java/com/mamully/toyProject/test/command/service/TestServiceTest.java
  toyProject/src/test/java/com/mamully/toyProject/test/query/service/TestQueryServiceTest.java
Labels: refactor, test, rename

#20 refactor 잘못된 코드 수정
  toyProject/src/main/java/com/mamully/toyProject/config/WebConfig.java
  toyProject/src/main/java/com/mamully/toyProject/config/Webconfig.java
Labels: refactor

#22 feat S3연동 및 테스트 코드 추가 완료
  docker-compose.yml
  toyProject/build.gradle
  toyProject/src/main/java/com/mamully/toyProject/common/s3/FileUploadDTO.java
  toyProject/src/main/java/com/mamully/toyProject/common/s3/FileUploadUtil.java
  toyProject/src/main/java/com/mamully/toyProject/config/S3Config.java
  toyProject/src/main/java/com/mamully/toyProject/test/command/controllers/TestController.java
  toyProject/src/main/resources/application.yml
Labels: feat, refactor, test

#36 feat Youtube Data API 연동
  toyProject/build.gradle
  toyProject/src/main/java/com/mamully/toyProject/common/youtube/YoutubeUtil.java
  toyProject/src/main/java/com/mamully/toyProject/config/YoutubeConfig.java
Labels: feat

#38 chore: Youtube API 구현 후 주석 처리
  toyProject/src/main/java/com/mamully/toyProject/common/youtube/YoutubeUtil.java
  toyProject/src/main/java/com/mamully/toyProject/config/YoutubeConfig.java
Labels: chore
